"""Pure iCal serialization for outbound calendar feeds.

Uses the ``icalendar`` library (RFC 5545 compliant) so we never hand-roll
fiddly bits like line folding, escaping, or DATE-only VALUE parameters.

Outbound feeds are date-granular (no time-of-day) per the operator's use
case — channels block whole days, and the iCal convention for date-only
VEVENTs is ``DTSTART;VALUE=DATE:YYYYMMDD`` with ``DTEND`` exclusive.

The PRODID identifies us as the source. Consumers (Airbnb / VRBO / etc.)
log this; helpful when we need to confirm a feed was generated by us.
"""
from __future__ import annotations

from datetime import datetime, timezone
from typing import Iterable

from icalendar import Calendar, Event

from app.models.listings.listing_blackout import ListingBlackout

_PRODID_TEMPLATE = "-//MyBookkeeper//listing {listing_id}//EN"


def serialize_blackouts(
    listing_id: str,
    blackouts: Iterable[ListingBlackout],
    *,
    now: datetime | None = None,
) -> bytes:
    """Build an iCalendar payload for a listing's blackouts.

    Returns raw bytes ready to put in an HTTP response body. The calling
    route layer sets ``Content-Type: text/calendar; charset=utf-8``.

    Each blackout becomes one VEVENT:
      - UID: ``blackout-<row-uuid>@mybookkeeper`` — stable across re-renders
        so consumers can dedup.
      - DTSTART;VALUE=DATE: starts_on
      - DTEND;VALUE=DATE: ends_on (exclusive — preserved from the row)
      - SUMMARY: "Blocked"
      - DTSTAMP: ``now`` in UTC. Required by RFC 5545.

    ``now`` is parameterised for tests so generated payloads are
    deterministic; production callers omit it and get the current UTC time.
    """
    cal = Calendar()
    cal.add("prodid", _PRODID_TEMPLATE.format(listing_id=listing_id))
    cal.add("version", "2.0")
    cal.add("calscale", "GREGORIAN")

    stamp = (now or datetime.now(timezone.utc)).astimezone(timezone.utc)

    for blackout in blackouts:
        event = Event()
        event.add("uid", f"blackout-{blackout.id}@mybookkeeper")
        event.add("dtstamp", stamp)
        event.add("summary", "Blocked")
        # Use the date-typed values directly. ``icalendar`` will emit
        # ``;VALUE=DATE:YYYYMMDD`` on serialization.
        event.add("dtstart", blackout.starts_on)
        event.add("dtend", blackout.ends_on)
        cal.add_component(event)

    return cal.to_ical()
