"""add_source_column_to_documents

Revision ID: 186c7b93cdc7
Revises: 25f4981a4ad0
Create Date: 2026-03-16 19:06:27.616710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '186c7b93cdc7'
down_revision: Union[str, None] = '25f4981a4ad0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('documents', sa.Column('source', sa.String(length=20), nullable=False, server_default='upload'))
    op.execute("UPDATE documents SET source = 'email' WHERE email_message_id IS NOT NULL")
    op.alter_column('documents', 'source', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'source')
    # ### end Alembic commands ###
