"""add_activity_periods_table_drop_active_dates

Revision ID: 25f4981a4ad0
Revises: 49205c839ba6
Create Date: 2026-03-16 18:54:12.588783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '25f4981a4ad0'
down_revision: Union[str, None] = '49205c839ba6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_activity_periods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('active_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('active_until', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # Migrate existing active_from/active_until data to activity_periods
    op.execute(
        "INSERT INTO property_activity_periods (property_id, active_from, active_until) "
        "SELECT id, active_from, active_until FROM properties "
        "WHERE active_from IS NOT NULL AND active_until IS NOT NULL"
    )
    op.drop_column('properties', 'active_until')
    op.drop_column('properties', 'active_from')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('active_from', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('properties', sa.Column('active_until', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_table('property_activity_periods')
    # ### end Alembic commands ###
