"""add_invoice_status_and_address

Revision ID: 34644601c086
Revises: 4579458512be
Create Date: 2026-03-14 22:14:54.344492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34644601c086'
down_revision: Union[str, None] = '4579458512be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('address', sa.String(length=500), nullable=True))
    op.add_column('invoices', sa.Column('status', sa.String(length=20), nullable=False, server_default='approved'))
    op.alter_column('invoices', 'status', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'status')
    op.drop_column('invoices', 'address')
    # ### end Alembic commands ###
