"""add_active_dates_to_properties

Revision ID: 49205c839ba6
Revises: aec60e16dff0
Create Date: 2026-03-16 18:48:11.170883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49205c839ba6'
down_revision: Union[str, None] = 'aec60e16dff0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('active_from', sa.DateTime(timezone=True), nullable=True))
    op.add_column('properties', sa.Column('active_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'active_until')
    op.drop_column('properties', 'active_from')
    # ### end Alembic commands ###
