"""add_document_type_to_documents

Revision ID: dfad38288858
Revises: 46271cb3dae2
Create Date: 2026-03-16 19:23:13.572617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfad38288858'
down_revision: Union[str, None] = '46271cb3dae2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('documents', sa.Column('document_type', sa.String(length=50), nullable=False, server_default='invoice'))
    op.alter_column('documents', 'document_type', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'document_type')
    # ### end Alembic commands ###
