"""add channels, channel_listings, listing_blackouts (PR 1.4 listings/channels)

Revision ID: j2k4l6m8n0p2
Revises: i1k3l6n8p0q2
Create Date: 2026-04-29

PR 1.4 of the rentals expansion. See RENTALS_PLAN.md §5.1 (channels).

Three new tables:

- ``channels`` — small reference table seeded with airbnb / vrbo /
  furnished_finder / rotating_room. ``id`` is a string slug (readable in
  URLs and logs).
- ``channel_listings`` — one row per (listing, channel) pair the host
  publishes on. Carries inbound iCal import URL + last-poll metadata, plus
  the outbound iCal export token used in the unauthenticated public URL.
- ``listing_blackouts`` — date-range blackouts. ``source`` is either
  ``manual`` (operator-entered) or a channel slug (imported via iCal poll).
  Partial UNIQUE on (listing_id, source, source_event_id) makes the inbound
  poll idempotent — a re-poll with the same VEVENT.UID is an UPSERT.

Migration is purely additive — existing tables untouched. Cross-table FKs:

- channel_listings.listing_id → listings.id ON DELETE CASCADE
- channel_listings.channel_id → channels.id ON DELETE RESTRICT
  (a channel referenced by any channel_listing cannot be deleted —
  protects against accidentally orphaning rows. New channels can still
  be added freely; deletion is the dangerous direction.)
- listing_blackouts.listing_id → listings.id ON DELETE CASCADE

The ``ical_export_token`` column has no default at the DDL level — it's
generated by the SQLAlchemy model (``secrets.token_urlsafe(24)``) on insert.
The UNIQUE constraint is the authoritative protection against the
extraordinarily-unlikely token collision.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "j2k4l6m8n0p2"
down_revision: Union[str, None] = "i1k3l6n8p0q2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Seed data MUST stay in sync with app.core.channel_constants.CHANNEL_SEEDS
# (single source of truth in code; this list mirrors it for the DDL-time
# INSERT). A test asserts the lists match.
_CHANNEL_SEEDS: tuple[tuple[str, str, bool, bool], ...] = (
    ("airbnb", "Airbnb", True, True),
    ("vrbo", "VRBO", True, True),
    ("furnished_finder", "Furnished Finder", True, True),
    ("rotating_room", "Rotating Room", False, False),
)


def upgrade() -> None:
    op.create_table(
        "channels",
        sa.Column("id", sa.String(length=40), primary_key=True),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column(
            "supports_ical_export", sa.Boolean(),
            nullable=False, server_default=sa.text("false"),
        ),
        sa.Column(
            "supports_ical_import", sa.Boolean(),
            nullable=False, server_default=sa.text("false"),
        ),
        sa.Column(
            "created_at", sa.DateTime(timezone=True),
            nullable=False, server_default=sa.func.now(),
        ),
    )

    # Idempotent seed — re-running the migration on an existing DB is a no-op
    # for already-present rows. ``ON CONFLICT DO NOTHING`` keeps the seed
    # safe to re-apply without altering existing flag values; intentional
    # changes to the flags must come via a follow-up migration.
    channels_table = sa.table(
        "channels",
        sa.column("id", sa.String),
        sa.column("name", sa.String),
        sa.column("supports_ical_export", sa.Boolean),
        sa.column("supports_ical_import", sa.Boolean),
    )
    op.bulk_insert(
        channels_table,
        [
            {
                "id": cid,
                "name": cname,
                "supports_ical_export": exp,
                "supports_ical_import": imp,
            }
            for (cid, cname, exp, imp) in _CHANNEL_SEEDS
        ],
    )

    op.create_table(
        "channel_listings",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("listing_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("channel_id", sa.String(length=40), nullable=False),
        sa.Column("external_url", sa.String(length=500), nullable=True),
        sa.Column("external_id", sa.String(length=120), nullable=True),
        sa.Column("ical_import_url", sa.String(length=1000), nullable=True),
        sa.Column("ical_import_secret_token", sa.String(length=255), nullable=True),
        sa.Column("last_imported_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_import_error", sa.Text(), nullable=True),
        sa.Column("ical_export_token", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True),
            nullable=False, server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True),
            nullable=False, server_default=sa.func.now(),
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"], ["listings.id"], ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["channel_id"], ["channels.id"], ondelete="RESTRICT",
        ),
        sa.UniqueConstraint(
            "listing_id", "channel_id",
            name="uq_channel_listings_listing_channel",
        ),
        sa.UniqueConstraint(
            "ical_export_token",
            name="uq_channel_listings_export_token",
        ),
    )
    op.create_index(
        "ix_channel_listings_listing_id", "channel_listings", ["listing_id"],
    )
    op.create_index(
        "ix_channel_listings_channel_id", "channel_listings", ["channel_id"],
    )
    op.create_index(
        "ix_channel_listings_import_due",
        "channel_listings",
        ["ical_import_url", "last_imported_at"],
        postgresql_where=sa.text("ical_import_url IS NOT NULL"),
    )

    op.create_table(
        "listing_blackouts",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("listing_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("starts_on", sa.Date(), nullable=False),
        sa.Column("ends_on", sa.Date(), nullable=False),
        sa.Column(
            "source", sa.String(length=40),
            nullable=False, server_default="manual",
        ),
        sa.Column("source_event_id", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True),
            nullable=False, server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True),
            nullable=False, server_default=sa.func.now(),
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"], ["listings.id"], ondelete="CASCADE",
        ),
        sa.CheckConstraint(
            "ends_on > starts_on", name="chk_listing_blackouts_date_range",
        ),
    )
    op.create_index(
        "ix_listing_blackouts_listing_id", "listing_blackouts", ["listing_id"],
    )
    op.create_index(
        "ix_listing_blackouts_listing_dates",
        "listing_blackouts",
        ["listing_id", "starts_on", "ends_on"],
    )
    # Partial unique — only enforced where source_event_id IS NOT NULL.
    # This is the idempotency key for the iCal poll: same VEVENT.UID + same
    # listing + same channel source = same row, regardless of how many
    # times we re-poll.
    op.create_index(
        "uq_listing_blackouts_source_uid",
        "listing_blackouts",
        ["listing_id", "source", "source_event_id"],
        unique=True,
        postgresql_where=sa.text("source_event_id IS NOT NULL"),
    )


def downgrade() -> None:
    op.drop_index("uq_listing_blackouts_source_uid", table_name="listing_blackouts")
    op.drop_index("ix_listing_blackouts_listing_dates", table_name="listing_blackouts")
    op.drop_index("ix_listing_blackouts_listing_id", table_name="listing_blackouts")
    op.drop_table("listing_blackouts")

    op.drop_index("ix_channel_listings_import_due", table_name="channel_listings")
    op.drop_index("ix_channel_listings_channel_id", table_name="channel_listings")
    op.drop_index("ix_channel_listings_listing_id", table_name="channel_listings")
    op.drop_table("channel_listings")

    op.drop_table("channels")
