"""The raid bot's icons — Discord application emojis with text fallbacks.

The art is ours: ``backend/data/discord_emojis/*.png``, generated by
``scripts/generate_discord_emojis.py`` (credits in NOTICE.md beside the
PNGs).  The post-deploy ``discord-sync-emojis`` CLI uploads it to the bot's
application; renderers read the process-wide registry through
:func:`current` and pass the snapshot into the pure message builders.

Logical names (each is a PNG file stem)
---------------------------------------
``<class>``                class icons (``CLASSES`` keys, e.g. ``warrior``)
``<class>_<spec>``         spec icons (e.g. ``druid_feral_tank``)
``role_<role>``            tank / healer / melee / ranged / dps
``status_<status>``        signed / late / tentative / bench / absence / queued
``info_<what>``            date / time / signups / leader / countdown / lock / globe
``ui_<what>``              button icons (``ui_gear``)
``tile_<char>``            title letters, digits, punctuation, ``tile_gap``

A name with no uploaded emoji renders its fallback, so the bot reads fine
before the first sync and if Discord is unreachable.
"""
from __future__ import annotations

from pathlib import Path
from typing import Final

from platform_shared.services.discord import (
    EMPTY_EMOJIS,
    EmojiRegistry,
    EmojiSet,
    expected_names,
    load_assets,
)

from app.core.config import settings
from app.services.discord import rest

EMOJI_DIR: Final = Path(__file__).resolve().parents[3] / "data" / "discord_emojis"

__all__ = ["EMOJI_DIR", "EMPTY_EMOJIS", "EmojiSet", "current", "registry", "start_refresh"]


async def _fetch() -> list[dict]:
    async with rest.make_rest_client() as client:
        return await rest.bounded(client.list_application_emojis(settings.discord_application_id))


def _build_registry() -> EmojiRegistry:
    return EmojiRegistry(_fetch, expected=expected_names(load_assets(EMOJI_DIR)))


registry: Final = _build_registry()


def current() -> EmojiSet:
    """The icons to render with right now (never blocks; may start a refresh).

    Empty when the bot is disabled — there is no application to list.
    """
    if not settings.discord_enabled:
        return EMPTY_EMOJIS
    return registry.current()


def start_refresh() -> None:
    """Warm the registry at startup without blocking boot."""
    current()
