import { test, expect, type APIRequestContext } from "./fixtures/auth";

/**
 * PR 3.3 — Applicant screening (KeyCheck redirect-only) E2E.
 *
 * Covers the host-driven flow:
 *  1. Seed an applicant via /test/seed-applicant.
 *  2. Open ApplicantDetail.
 *  3. Verify the Screening section renders with Run + Upload buttons.
 *  4. Upload a fake PDF report via the multipart endpoint.
 *  5. Verify the new screening_result row appears in the list.
 *  6. Verify a 'fail' upload requires the adverse-action snippet.
 *
 * Cleanup deletes seeded applicants + screening_results per
 * ``feedback_clean_test_data``.
 */

async function seedApplicant(api: APIRequestContext, runId: number): Promise<string> {
  const res = await api.post("/test/seed-applicant", {
    data: {
      legal_name: `E2E Screening ${runId}`,
      stage: "lead",
      seed_event: true,
    },
  });
  if (!res.ok()) {
    throw new Error(`seedApplicant failed: ${res.status()} ${await res.text()}`);
  }
  const body = (await res.json()) as { id: string };
  return body.id;
}

async function deleteApplicant(api: APIRequestContext, id: string): Promise<void> {
  await api.delete(`/test/applicants/${id}`).catch(() => {});
}

async function deleteScreeningResult(api: APIRequestContext, id: string): Promise<void> {
  await api.delete(`/test/screening/${id}`).catch(() => {});
}

/** Minimal valid PDF — two pages, a few bytes of content. Generated bytes
 * pulled from a hand-written PDF skeleton so libmagic + the header sniff
 * both classify it as application/pdf. */
function buildMinimalPdf(): Buffer {
  return Buffer.from(
    "%PDF-1.4\n" +
    "1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj\n" +
    "2 0 obj<</Type/Pages/Count 0/Kids[]>>endobj\n" +
    "xref\n0 3\n0000000000 65535 f\n0000000009 00000 n\n0000000052 00000 n\n" +
    "trailer<</Size 3/Root 1 0 R>>\nstartxref\n96\n%%EOF\n",
    "ascii",
  );
}

test.describe("Applicant screening (PR 3.3 — KeyCheck redirect-only)", () => {
  test("upload flow: seed applicant, open detail, upload pass result, verify list", async ({
    authedPage: page,
    api,
  }) => {
    const runId = Date.now();
    const seededApplicantIds: string[] = [];
    const seededScreeningIds: string[] = [];

    try {
      const applicantId = await seedApplicant(api, runId);
      seededApplicantIds.push(applicantId);

      await page.goto(`/applicants/${applicantId}`);
      await page.waitForLoadState("networkidle");
      await expect(page.getByTestId("screening-section")).toBeVisible({
        timeout: 10000,
      });

      // The "Run KeyCheck" button is visible (auth fixture is OWNER role).
      await expect(page.getByTestId("run-screening-button")).toBeVisible();

      // Empty state until we upload — sometimes the API hasn't returned yet
      // by the time we land, so wait for either the list or the empty marker.
      await expect(
        page.getByTestId("screening-results-empty"),
      ).toBeVisible({ timeout: 5000 });

      // Upload via the API (skips the modal — we verify the modal in
      // unit tests; this is the behavioural E2E for the upload pipeline +
      // list refresh).
      const pdf = buildMinimalPdf();
      const uploadRes = await api.post(
        `/applicants/${applicantId}/screening/upload-result`,
        {
          multipart: {
            file: { name: "report.pdf", mimeType: "application/pdf", buffer: pdf },
            status: "pass",
          },
        },
      );
      expect(uploadRes.status()).toBe(201);
      const uploadBody = (await uploadRes.json()) as {
        id: string;
        provider: string;
        status: string;
      };
      seededScreeningIds.push(uploadBody.id);
      expect(uploadBody.provider).toBe("keycheck");
      expect(uploadBody.status).toBe("pass");

      // Refresh the page so the cache picks up the new row.
      await page.reload();
      await page.waitForLoadState("networkidle");

      const list = page.getByTestId("screening-results-list");
      await expect(list).toBeVisible({ timeout: 10000 });
      await expect(
        page.getByTestId(`screening-result-${uploadBody.id}`),
      ).toBeVisible();
    } finally {
      for (const id of seededScreeningIds) await deleteScreeningResult(api, id);
      for (const id of seededApplicantIds) await deleteApplicant(api, id);
    }
  });

  test("upload with fail status requires adverse_action_snippet (server-side 422)", async ({
    api,
  }) => {
    const runId = Date.now();
    const seededApplicantIds: string[] = [];

    try {
      const applicantId = await seedApplicant(api, runId);
      seededApplicantIds.push(applicantId);

      const pdf = buildMinimalPdf();
      // Missing snippet → backend 422.
      const badRes = await api.post(
        `/applicants/${applicantId}/screening/upload-result`,
        {
          multipart: {
            file: { name: "report.pdf", mimeType: "application/pdf", buffer: pdf },
            status: "fail",
          },
        },
      );
      expect(badRes.status()).toBe(422);
    } finally {
      for (const id of seededApplicantIds) await deleteApplicant(api, id);
    }
  });

  test("redirect endpoint returns the configured KeyCheck URL", async ({ api }) => {
    const runId = Date.now();
    const seededApplicantIds: string[] = [];

    try {
      const applicantId = await seedApplicant(api, runId);
      seededApplicantIds.push(applicantId);

      const res = await api.get(`/applicants/${applicantId}/screening/redirect`);
      expect(res.status()).toBe(200);
      const body = (await res.json()) as { redirect_url: string; provider: string };
      expect(body.provider).toBe("keycheck");
      expect(body.redirect_url).toMatch(/^https?:\/\//);
    } finally {
      for (const id of seededApplicantIds) await deleteApplicant(api, id);
    }
  });
});
