from app.repositories.extraction import extraction_repo
from app.repositories.extraction import extraction_prompt_repo
from app.repositories.documents import document_repo
from app.repositories.email import email_queue_repo
from app.repositories.email import processed_email_repo
from app.repositories.email import sync_log_repo
from app.repositories.transactions import transaction_repo
from app.repositories.transactions import reservation_repo
from app.repositories.transactions import reconciliation_repo
from app.repositories.transactions import summary_repo
from app.repositories.tax import tax_return_repo
from app.repositories.tax import tax_form_repo
from app.repositories.tax import tax_year_profile_repo
from app.repositories.tax import cost_basis_lot_repo
from app.repositories.tax import tax_advisor_repo
from app.repositories.integrations import integration_repo
from app.repositories.integrations import plaid_repo
from app.repositories.system import system_event_repo
from app.repositories.system import usage_log_repo
from app.repositories.system import audit_repo
from app.repositories.system import admin_repo
from app.repositories.system import cost_repo
from app.repositories.organization import organization_repo
from app.repositories.organization import activity_repo
from app.repositories.organization import tax_profile_repo
from app.repositories.organization import taxpayer_profile_repo
from app.repositories.properties import property_repo
from app.repositories.properties import tenant_repo
from app.repositories.properties import lease_repo
from app.repositories.user import user_repo
from app.repositories.classification import classification_rule_repo
from app.repositories.demo import demo_repo
from app.repositories.analytics import utility_trends_repo
from app.repositories import db_admin_repo
