"""WoW Forever raid consumables selector.

Loads the committed ``backend/data/wow/raid_consumables.json`` (generated by
``python -m scripts.wow_consumables.build``) once per process and exposes a
pure ``select_consumables`` function suitable for Discord bot use.

Role normalisation
------------------
Roles accepted:  ``"tank"``, ``"healer"``, ``"dps_physical"``, ``"dps_caster"``
Special values accepted in spec ``roles`` lists:
  * ``"dps"``   → matches both ``dps_physical`` and ``dps_caster``
  * ``"melee"`` → matches ``dps_physical``

If ``role`` is ``None`` and ``wow_class`` is given, the class default is used::

    warrior / rogue / hunter / druid / shaman / paladin → dps_physical
    mage / warlock                                       → dps_caster
    priest                                               → healer

If ``wow_class`` is ``None``: only ``always`` + ``role_baseline`` + ``raid_specific``
are included (no class extras, no food).

Deduplication
-------------
When the same item_id appears in multiple sections (e.g. Major Healing Potion
in ``always`` AND ``role_baseline.tank``), the entry with the HIGHEST tier is
kept.  Ties in tier are broken by source specificity (raid_specific beats
class_extras beats role_baseline/food beats always).  The ``why`` comes from
the winning entry.
"""
from __future__ import annotations

import json
from dataclasses import dataclass, field
from functools import lru_cache
from pathlib import Path
from typing import Literal

# Path: app/services/wow/ → parents[3] = backend/
_DATA_PATH = Path(__file__).resolve().parents[3] / "data" / "wow" / "raid_consumables.json"

Tier = Literal["essential", "recommended", "tryhard"]

_TIER_RANK: dict[str, int] = {"essential": 3, "recommended": 2, "tryhard": 1}

# Source-specificity rank for deduplication tie-breaking.
# Higher = more specific.
_SOURCE_RANK = {
    "always": 1,
    "food": 2,
    "role_baseline": 3,
    "class_extras": 4,
    "raid_specific": 5,
}

# Default role per class when role=None.
_DEFAULT_ROLE: dict[str, str] = {
    "warrior": "dps_physical",
    "rogue": "dps_physical",
    "hunter": "dps_physical",
    "mage": "dps_caster",
    "warlock": "dps_caster",
    "priest": "healer",
    "druid": "dps_physical",   # feral default
    "shaman": "dps_physical",  # enhancement default
    "paladin": "dps_physical", # retribution default
}

# Physical vs caster split for auto-role resolution.
_PHYSICAL_CLASSES = frozenset({"warrior", "rogue", "hunter", "druid", "shaman", "paladin"})
_CASTER_CLASSES = frozenset({"mage", "warlock"})


class UnknownRaidError(KeyError):
    """Raised when ``raid_key`` is not present in the consumables dataset."""


@dataclass(frozen=True)
class ConsumableItem:
    item_id: int
    name: str
    why: str
    tier: Tier
    wowhead_url: str


@dataclass
class ConsumableChecklist:
    """Deduplicated consumable recommendations for a given raid / class / role."""

    raid_key: str
    raid_name: str
    classic_advice: bool  # True → prepend "Classic advice — may differ in Forever"
    essential: list[ConsumableItem] = field(default_factory=list)
    recommended: list[ConsumableItem] = field(default_factory=list)
    tryhard: list[ConsumableItem] = field(default_factory=list)

    def all_items(self) -> list[ConsumableItem]:
        """All items in tier order: essential → recommended → tryhard."""
        return [*self.essential, *self.recommended, *self.tryhard]


@lru_cache(maxsize=1)
def _load() -> dict:
    """Load and cache the raid consumables JSON."""
    return json.loads(_DATA_PATH.read_text(encoding="utf-8"))


def wowhead_url(item_id: int) -> str:
    """Return the Wowhead URL for a Classic / Forever item."""
    return f"https://www.wowhead.com/classic/item={item_id}"


def _role_matches(effective_role: str | None, item_roles: list[str]) -> bool:
    """Return True if ``effective_role`` satisfies the item's role constraint list.

    Normalisation:
      "dps"   → matches dps_physical and dps_caster
      "melee" → matches dps_physical
    """
    if effective_role is None:
        return True  # no role set → no filtering
    expanded: set[str] = {
        "dps_physical": {"dps_physical", "dps", "melee"},
        "dps_caster": {"dps_caster", "dps"},
        "tank": {"tank"},
        "healer": {"healer"},
    }.get(effective_role, {effective_role})
    return any(r in expanded for r in item_roles)


def _class_matches(wow_class: str | None, item_classes: list[str]) -> bool:
    if wow_class is None:
        return True  # no class → no filtering
    return wow_class.lower() in {c.lower() for c in item_classes}


def _item_matches(item: dict, wow_class: str | None, effective_role: str | None) -> bool:
    if item.get("roles") and not _role_matches(effective_role, item["roles"]):
        return False
    if item.get("classes") and not _class_matches(wow_class, item["classes"]):
        return False
    return True


def _to_consumable(item: dict) -> ConsumableItem:
    return ConsumableItem(
        item_id=item["item_id"],
        name=item["name"],
        why=item["why"],
        tier=item["tier"],
        wowhead_url=item.get("wowhead_url", wowhead_url(item["item_id"])),
    )


def select_consumables(
    raid_key: str,
    wow_class: str | None,
    role: str | None,
) -> ConsumableChecklist:
    """Return deduplicated consumable recommendations.

    Parameters
    ----------
    raid_key:
        One of the raid keys in ``raids`` (e.g. ``"barrow_deeps"``).
    wow_class:
        Lowercase WoW class name (``"warrior"``, ``"priest"``, …) or ``None``
        for a class-agnostic recommendation.
    role:
        ``"tank"``, ``"healer"``, ``"dps_physical"``, ``"dps_caster"``, or
        ``None`` to use the class default.

    Raises
    ------
    UnknownRaidError
        If ``raid_key`` is not present in the dataset.
    """
    data = _load()

    if raid_key not in data["raids"]:
        valid = ", ".join(sorted(data["raids"]))
        raise UnknownRaidError(
            f"Unknown raid key {raid_key!r}. Valid keys: {valid}"
        )

    raid_info = data["raids"][raid_key]
    classic_advice = raid_info["advice_source"] == "classic"

    # Resolve effective role.
    effective_role = role
    if effective_role is None and wow_class is not None:
        effective_role = _DEFAULT_ROLE.get(wow_class.lower())

    # Collect candidates as (source_rank, tier_rank, item_dict).
    # Higher ranks win when deduplicating.
    Candidate = tuple[int, int, dict]
    candidates: list[Candidate] = []

    def _add(source: str, items: list[dict]) -> None:
        src_rank = _SOURCE_RANK[source]
        for item in items:
            tier_rank = _TIER_RANK.get(item.get("tier", ""), 0)
            candidates.append((src_rank, tier_rank, item))

    # 1. Always section — everyone.
    _add("always", [
        item for item in data["always"]
        if _item_matches(item, wow_class, effective_role)
    ])

    if wow_class is not None:
        # 2. Food.
        _add("food", data["food"].get("raid", []))
        if effective_role in data["food"]:
            _add("food", data["food"][effective_role])

        # 3. Role baseline.
        if effective_role and effective_role in data["role_baseline"]:
            _add("role_baseline", [
                item for item in data["role_baseline"][effective_role]
                if _item_matches(item, wow_class, effective_role)
            ])

        # 4. Class extras.
        cls_lower = wow_class.lower()
        if cls_lower in data["class_extras"]:
            _add("class_extras", [
                item for item in data["class_extras"][cls_lower]
                if _item_matches(item, wow_class, effective_role)
            ])
    else:
        # Class None: role baseline only (no food, no class extras).
        if effective_role and effective_role in data["role_baseline"]:
            _add("role_baseline", [
                item for item in data["role_baseline"][effective_role]
                if _item_matches(item, None, effective_role)
            ])

    # 5. Raid-specific.
    for item in data["raid_specific"].get(raid_key, []):
        matches = _item_matches(item, wow_class, effective_role)
        if matches:
            src_rank = _SOURCE_RANK["raid_specific"]
            tier_rank = _TIER_RANK.get(item.get("tier", ""), 0)
            candidates.append((src_rank, tier_rank, item))

    # --- Deduplicate by item_id: highest tier wins; tie → most specific source. ---
    best: dict[int, Candidate] = {}
    for src_rank, tier_rank, item in candidates:
        item_id = item["item_id"]
        if item_id not in best:
            best[item_id] = (src_rank, tier_rank, item)
        else:
            curr_src, curr_tier, _ = best[item_id]
            if tier_rank > curr_tier or (tier_rank == curr_tier and src_rank > curr_src):
                best[item_id] = (src_rank, tier_rank, item)

    # --- Group by tier. ---
    essential: list[ConsumableItem] = []
    recommended: list[ConsumableItem] = []
    tryhard: list[ConsumableItem] = []

    for _, _, item in sorted(best.values(), key=lambda c: (-c[0], c[2]["item_id"])):
        ci = _to_consumable(item)
        if ci.tier == "essential":
            essential.append(ci)
        elif ci.tier == "recommended":
            recommended.append(ci)
        else:
            tryhard.append(ci)

    return ConsumableChecklist(
        raid_key=raid_key,
        raid_name=raid_info["name"],
        classic_advice=classic_advice,
        essential=sorted(essential, key=lambda c: c.item_id),
        recommended=sorted(recommended, key=lambda c: c.item_id),
        tryhard=sorted(tryhard, key=lambda c: c.item_id),
    )
