"""The raid posts' banners — our own art, served by the API for Discord to show.

The art is ours: ``backend/data/raid_banners/<raid key>.png``, generated by
``scripts/generate_raid_banners.py`` (credits in NOTICE.md beside the PNGs).
A raid post's embed shows its raid's banner as the embed image, under the
columns and above the footer, like Raid-Helper's.

Discord fetches an embed image from its URL through its media proxy and
caches it by URL, so the URL carries a hash of the image: new art, new URL.
``GET /discord/raid-banners/<raid key>.png`` (``app/api/discord_raid_banners.py``)
serves the bytes, loaded once at import.

Discord can only fetch a public https URL, so posts carry banners only when
the app's public origin (``settings.frontend_url``) is https — production.
Local dev and tests post without them.  The raid's web page shows the same
art from this site by path (``banner_path``), so it shows it locally too.
"""
from __future__ import annotations

import hashlib
import logging
from dataclasses import dataclass
from pathlib import Path
from typing import Final

from app.core.config import settings
from app.services.wow.raid_web_links import public_origin

logger = logging.getLogger(__name__)

BANNER_DIR: Final = Path(__file__).resolve().parents[3] / "data" / "raid_banners"
ROUTE_PREFIX: Final = "/discord/raid-banners"
VERSION_CHARS: Final = 8


@dataclass(frozen=True)
class Banner:
    raid_key: str
    png: bytes
    version: str  # the start of the image's SHA-256

    @property
    def file_name(self) -> str:
        return f"{self.raid_key}.png"


def load_banners(directory: Path) -> dict[str, Banner]:
    """Every ``<raid key>.png`` in *directory*, by raid key."""
    banners: dict[str, Banner] = {}
    for path in sorted(directory.glob("*.png")):
        png = path.read_bytes()
        banners[path.stem] = Banner(path.stem, png, hashlib.sha256(png).hexdigest()[:VERSION_CHARS])
    return banners


BANNERS: Final = load_banners(BANNER_DIR)
_BY_FILE_NAME: Final = {banner.file_name: banner for banner in BANNERS.values()}


def banner_for_file(file_name: str) -> Banner | None:
    """The banner served as *file_name* (``onyxia.png``); None for anything else."""
    return _BY_FILE_NAME.get(file_name)


def banner_path(raid_key: str) -> str | None:
    """A raid's banner as a path on this site (``/api/discord/raid-banners/…``); None without art."""
    banner = BANNERS.get(raid_key)
    if banner is None:
        return None
    return f"{settings.backend_root_path}{ROUTE_PREFIX}/{banner.file_name}?v={banner.version}"


def banner_url(raid_key: str) -> str | None:
    """The public URL of a raid's banner, for a post's embed.

    None when the raid has no banner or the app has no public https origin.
    """
    origin = public_origin()
    path = banner_path(raid_key)
    if origin is None or path is None:
        return None
    return f"{origin}{path}"


def banners_off_reason() -> str | None:
    """Why raid posts would go out without banners; None when they show them."""
    if not BANNERS:
        return f"no banner art in {BANNER_DIR}"
    if public_origin() is None:
        return "FRONTEND_URL is not an https origin"
    return None


def log_if_off() -> None:
    """Say at startup when posts will lack banners — a warning in production, where they should show."""
    reason = banners_off_reason()
    if reason is None:
        return
    level = logging.WARNING if settings.environment == "production" else logging.INFO
    logger.log(level, "Raid posts will go out without banners: %s", reason)
