"""Auth event type constants used by every app's auth-event audit log."""


class AuthEventType:
    LOGIN_SUCCESS = "login.success"
    LOGIN_FAILURE = "login.failure"
    LOGIN_BLOCKED_LOCKED = "login.blocked.locked"
    LOGIN_BLOCKED_UNVERIFIED = "login.blocked.unverified"
    LOGIN_BLOCKED_RATE_LIMIT = "login.blocked.rate_limit"
    REGISTER_SUCCESS = "register.success"
    EMAIL_VERIFY_SUCCESS = "email_verify.success"
    EMAIL_VERIFY_RESEND = "email_verify.resend"
    PASSWORD_RESET_REQUEST = "password_reset.request"
    PASSWORD_RESET_SUCCESS = "password_reset.success"
    PASSWORD_CHANGE_SUCCESS = "password_change.success"
    TOTP_ENABLED = "totp.enabled"
    TOTP_DISABLED = "totp.disabled"
    TOTP_VERIFY_SUCCESS = "totp.verify.success"
    TOTP_VERIFY_FAILURE = "totp.verify.failure"
    TOTP_RECOVERY_USED = "totp.recovery.used"
    OAUTH_CONNECT = "oauth.connect"
    OAUTH_DISCONNECT = "oauth.disconnect"
    ACCOUNT_DELETED = "account.deleted"
    DATA_EXPORTED = "data.exported"
