"""Build the WoW Forever gold-farm data.

    python -m scripts.wow_gold.build

Writes ``frontend/src/games/wow-forever/data/gold/classic/goldFarms.json``:
the best places to farm gold at each level, worked out from cmangos
classic-db (GPL-3.0, pinned commit — see that folder's LICENSE) — the coin
and vendor value of what each ordinary mob drops, where it's packed, and the
cloth, greens, recipes and leather on top. Forever may differ; the page says
so. Never hand-edit the JSON; re-run this.
"""
from __future__ import annotations

import shutil
from pathlib import Path

from scripts.wow_gold.farms import FARM_COLUMNS, TABLES, GoldFarms
from scripts.wow_world_map.build import write_json
from scripts.wow_world_map.factions import FactionTemplate
from scripts.wow_world_map.map_art import WorldMapArt
from scripts.wow_world_map.sources import CMANGOS_COMMIT, cmangos_dump, wago_table
from scripts.wow_world_map.sql_dump import read_dump
from scripts.wow_world_map.zones import load_zones

BACKEND_DIR = Path(__file__).resolve().parents[2]
WOW_DATA_DIR = BACKEND_DIR.parent / "frontend" / "src" / "games" / "wow-forever" / "data"
CLASSIC_DIR = WOW_DATA_DIR / "gold" / "classic"
CLASSIC_LICENSE = WOW_DATA_DIR / "worldMap" / "classic" / "LICENSE"

# The page shows a level's best few places; keep every row that makes some level's list.
SHOWN_PER_LEVEL = 6
# Mobs from 3 levels below you to 1 above: grey mobs give no XP, +2 and up resist and dodge.
LEVELS_BELOW = 3
LEVELS_ABOVE = 1
MAX_LEVEL = 60

README = """# Gold farms — Classic data

`goldFarms.json` lists ordinary mobs worth farming for gold, at the spot each
is packed most densely: the coin they drop (`creature_template`
MinLootGold/MaxLootGold), the vendor value of their loot weighed by drop
chance (`creature_loot_template` + `reference_loot_template`, `item_template`
SellPrice), the cloth, greens and recipes to expect, and what skinning them
gives (`skinning_loot_template`). Spawns and respawn times from `creature`.
From [cmangos classic-db](https://github.com/cmangos/classic-db) at commit
`{commit}`, licensed GPL-3.0 — see `LICENSE`. No cmangos code is used.
Forever may differ; the page labels it as Classic.

Generated by `backend/scripts/wow_gold/build.py`. Never hand-edit.
"""


def gold_per_hour(row: dict[str, object], skinning: bool) -> float:
    per_kill = float(row["coin"]) + float(row["vendor"]) + (float(row["skinVendor"]) if skinning else 0.0)
    return per_kill * float(row["killsPerHour"])


def cloth_per_hour(row: dict[str, object]) -> float:
    return float(row["clothPerKill"]) * float(row["killsPerHour"])


def shown_rows(rows: list[list[object]]) -> list[list[object]]:
    """The rows on some level's list (most gold with or without Skinning, most cloth), one per place."""
    named = [dict(zip(FARM_COLUMNS, r)) for r in rows]
    rankings = [
        lambda r: gold_per_hour(r, False),
        lambda r: gold_per_hour(r, True),
        cloth_per_hour,
    ]
    keep: set[int] = set()
    for level in range(1, MAX_LEVEL + 1):
        fits = [r for r in named if int(r["maxLevel"]) >= level - LEVELS_BELOW and int(r["minLevel"]) <= level + LEVELS_ABOVE]
        for score in rankings:
            places: set[tuple[object, object]] = set()
            for r in sorted(fits, key=lambda r: (-score(r), r["npcId"])):
                if score(r) <= 0:
                    break
                place = (r["zone"], r["subzone"] or r["npcId"])
                if place in places:
                    continue
                places.add(place)
                keep.add(int(r["npcId"]))
                if len(places) == SHOWN_PER_LEVEL:
                    break
    return [r for r in rows if int(r[0]) in keep]


def main() -> None:
    tables = read_dump(cmangos_dump(), TABLES)
    reactions = {int(r["ID"]): FactionTemplate.from_csv_row(r) for r in wago_table("FactionTemplate")}
    _, zone_bounds = load_zones()
    farms = GoldFarms(tables, reactions, zone_bounds, WorldMapArt())
    rows = shown_rows(farms.farms())
    zones = {str(r[5]): farms.zone_names[int(r[5])] for r in rows}
    write_json(CLASSIC_DIR / "goldFarms.json", {
        "source": f"cmangos/classic-db@{CMANGOS_COMMIT}",
        "columns": FARM_COLUMNS,
        "zones": dict(sorted(zones.items(), key=lambda kv: int(kv[0]))),
        "farms": rows,
    })
    shutil.copyfile(CLASSIC_LICENSE, CLASSIC_DIR / "LICENSE")
    (CLASSIC_DIR / "README.md").write_text(README.format(commit=CMANGOS_COMMIT), encoding="utf-8")
    print(f"{len(rows)} farm spots -> {CLASSIC_DIR}")


if __name__ == "__main__":
    main()
