"""PDF generation for rent receipts.

Pure function — no DB I/O, no side effects. Takes the data needed for the
receipt and returns raw PDF bytes.

Uses ``reportlab`` (already a declared dep from PR #210). Layout:

  ┌─────────────────────────────────────────────────────────┐
  │  RENT RECEIPT          R-2026-0001          2026-05-01  │
  │                                                         │
  │  From (Tenant)         To (Landlord)                    │
  │  Jane Doe              John Smith                       │
  │  jane@example.com                                       │
  │                                                         │
  │  Property: 123 Main St, Springfield, IL                 │
  │  Period:   May 1–31, 2026                               │
  │                                                         │
  │  ┌──────────────────────────────────────────────────┐   │
  │  │   AMOUNT RECEIVED         $1,500.00              │   │
  │  └──────────────────────────────────────────────────┘   │
  │                                                         │
  │  Payment method: Check                                  │
  │                                                         │
  │  ─────────────────────────────────────────────────────  │
  │  Generated by MyBookkeeper · mybookkeeper.app          │
  └─────────────────────────────────────────────────────────┘
"""
from __future__ import annotations

import io
from dataclasses import dataclass
from datetime import date
from decimal import Decimal

from reportlab.lib import colors
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.units import inch
from reportlab.pdfgen.canvas import Canvas


@dataclass(frozen=True)
class ReceiptData:
    receipt_number: str       # e.g. "R-2026-0001"
    receipt_date: date        # date the receipt is issued (usually today)
    payer_name: str           # tenant's legal name
    payer_email: str | None   # tenant's email (shown on receipt)
    landlord_name: str        # host's name
    property_address: str     # full address from the listing
    period_start: date        # period covered start
    period_end: date          # period covered end
    amount: Decimal           # payment amount
    payment_method: str | None  # e.g. "check", "bank_transfer"


def _format_period(start: date, end: date) -> str:
    """Format the period as ``May 1–31, 2026`` or ``Apr 15 – May 14, 2026``."""
    if start.year == end.year and start.month == end.month:
        return f"{start.strftime('%B')} {start.day}–{end.day}, {start.year}"
    return f"{start.strftime('%b')} {start.day} – {end.strftime('%b')} {end.day}, {end.year}"


def _format_payment_method(method: str | None) -> str:
    labels = {
        "check": "Check",
        "credit_card": "Credit card",
        "bank_transfer": "Bank transfer",
        "cash": "Cash",
        "platform_payout": "Platform payout",
        "other": "Other",
    }
    if method is None:
        return "—"
    return labels.get(method, method.replace("_", " ").capitalize())


def generate_receipt_pdf(data: ReceiptData) -> bytes:
    """Return raw PDF bytes for a single-page rent receipt."""
    buf = io.BytesIO()
    c = Canvas(buf, pagesize=LETTER)
    width, height = LETTER

    margin = 0.75 * inch
    content_width = width - 2 * margin
    y = height - margin

    # ── Header bar ──────────────────────────────────────────────────────────
    c.setFillColor(colors.HexColor("#1e293b"))  # slate-800
    c.rect(margin, y - 0.55 * inch, content_width, 0.55 * inch, fill=1, stroke=0)

    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 14)
    c.drawString(margin + 0.15 * inch, y - 0.38 * inch, "RENT RECEIPT")

    c.setFont("Helvetica", 11)
    c.drawCentredString(width / 2, y - 0.38 * inch, data.receipt_number)

    c.setFont("Helvetica", 10)
    receipt_date_str = data.receipt_date.strftime("%B %d, %Y")
    c.drawRightString(margin + content_width - 0.15 * inch, y - 0.38 * inch, receipt_date_str)

    y -= 0.55 * inch + 0.3 * inch  # move below header + gap

    # ── Payer / Landlord two-column block ────────────────────────────────────
    col_left = margin
    col_right = margin + content_width / 2 + 0.1 * inch

    c.setFillColor(colors.HexColor("#64748b"))  # slate-500
    c.setFont("Helvetica-Bold", 8)
    c.drawString(col_left, y, "RECEIVED FROM")
    c.drawString(col_right, y, "RECEIVED BY")
    y -= 0.18 * inch

    c.setFillColor(colors.HexColor("#0f172a"))  # slate-900
    c.setFont("Helvetica-Bold", 11)
    c.drawString(col_left, y, data.payer_name)
    c.drawString(col_right, y, data.landlord_name)
    y -= 0.2 * inch

    if data.payer_email:
        c.setFont("Helvetica", 9)
        c.setFillColor(colors.HexColor("#64748b"))
        c.drawString(col_left, y, data.payer_email)
        y -= 0.18 * inch

    y -= 0.2 * inch  # spacer

    # ── Property / Period ────────────────────────────────────────────────────
    def label_value(label: str, value: str) -> None:
        nonlocal y
        c.setFont("Helvetica-Bold", 9)
        c.setFillColor(colors.HexColor("#64748b"))
        c.drawString(col_left, y, label)
        c.setFont("Helvetica", 9)
        c.setFillColor(colors.HexColor("#0f172a"))
        c.drawString(col_left + 1.0 * inch, y, value)
        y -= 0.18 * inch

    label_value("Property:", data.property_address)
    label_value("Period:", _format_period(data.period_start, data.period_end))

    y -= 0.25 * inch  # spacer before amount box

    # ── Amount box ───────────────────────────────────────────────────────────
    box_height = 0.6 * inch
    c.setFillColor(colors.HexColor("#f1f5f9"))  # slate-100
    c.setStrokeColor(colors.HexColor("#e2e8f0"))  # slate-200
    c.rect(margin, y - box_height, content_width, box_height, fill=1, stroke=1)

    c.setFillColor(colors.HexColor("#64748b"))
    c.setFont("Helvetica-Bold", 9)
    c.drawString(margin + 0.2 * inch, y - 0.22 * inch, "AMOUNT RECEIVED")

    c.setFillColor(colors.HexColor("#0f172a"))
    c.setFont("Helvetica-Bold", 18)
    amount_str = f"${data.amount:,.2f}"
    c.drawRightString(margin + content_width - 0.2 * inch, y - 0.38 * inch, amount_str)

    y -= box_height + 0.25 * inch

    # ── Payment method ────────────────────────────────────────────────────────
    label_value("Payment method:", _format_payment_method(data.payment_method))

    # ── Footer ────────────────────────────────────────────────────────────────
    c.setStrokeColor(colors.HexColor("#e2e8f0"))
    c.line(margin, margin + 0.35 * inch, margin + content_width, margin + 0.35 * inch)
    c.setFont("Helvetica", 7)
    c.setFillColor(colors.HexColor("#94a3b8"))  # slate-400
    c.drawCentredString(
        width / 2,
        margin + 0.15 * inch,
        "Generated by MyBookkeeper · mybookkeeper.app",
    )

    c.save()
    return buf.getvalue()
