import type { Confidence } from "@/games/wow-forever/data/professions/professionTypes";

export const CRAFTING_PROFESSION = { tailoring: "tailoring", enchanting: "enchanting" } as const;
export type CraftingProfession = (typeof CRAFTING_PROFESSION)[keyof typeof CRAFTING_PROFESSION];

export interface CraftReagent {
  id: number;
  name: string;
  count: number;
}

/** How a recipe is learned, as the generated data says. */
export type RecipeLearn =
  | { source: "start"; skill: 1 }
  | { source: "item"; skill: number; itemId: number; item: string }
  | { source: "trainer" };

/**
 * One recipe from the Forever beta client — GENERATED by
 * `python -m scripts.wow_professions.build`. `yellow` / `grey` are the skill
 * where it turns yellow / grey (green is half-way).
 */
export interface CraftRecipe {
  spell: number;
  name: string;
  yellow: number;
  grey: number;
  reagents: CraftReagent[];
  creates?: { id: number; name: string; count: number; quality: number };
  /** An uncommon+ weapon or armour piece an enchanter can break down. */
  disenchantable?: true;
  /** An enchant — makes no item. */
  enchant?: true;
  /** Must be in your bags (Enchanting's runed rods). */
  tool?: { id: number; name: string };
  learn: RecipeLearn;
  newInForever?: true;
  /** Classic Era's numbers, when Forever changed them. */
  classic?: { yellow: number; grey: number; reagents?: CraftReagent[] };
}

export interface CraftingFile {
  source: string;
  skillLine: number;
  /** Reagent item id -> the profession that makes it ("Tailoring" for bolts). */
  madeBy: Record<string, string>;
  recipes: CraftRecipe[];
}

/** Recipe spell -> skill a Classic trainer asks, and the Forever estimate from it. */
export type TrainerSkills = Record<string, { classic: number; forever: number }>;

/** One row of a hand-picked leveling route: craft `spell` from skill `from` to `to`. */
export interface CraftRouteStep {
  kind: "craft";
  spell: number;
  from: number;
  to: number;
  note?: string;
  confidence: Confidence;
}

/** The end of a route where no single recipe is safe to recommend yet. */
export interface CraftRouteOptions {
  kind: "options";
  from: number;
  to: number;
  title: string;
  intro: string;
  options: readonly { spell: number; detail: string }[];
  confidence: Confidence;
}

export type CraftRouteEntry = CraftRouteStep | CraftRouteOptions;

/** Where you learn a recipe on the route. */
export type LearnAt =
  | { kind: "start" }
  | { kind: "trainer"; skill: number; estimated: boolean }
  | { kind: "item"; skill: number; itemId: number; item: string };

/** Where a shown row came from: picked for your prices, or the hand-written route. */
export type RouteRowSource = "priced" | "default";

/** A route step joined to its recipe, with how many times to craft it. */
export interface ResolvedCraftStep {
  step: CraftRouteStep;
  recipe: CraftRecipe;
  crafts: number;
  learn: LearnAt;
  /** Set once you've entered prices: which route this row is from. */
  source?: RouteRowSource;
  /** Expected copper for the row from your skill on; absent when a material has no price. */
  cost?: number;
  /** The materials that still need a price before this row has a cost. */
  missing?: readonly { id: number; name: string }[];
}

export type ResolvedRouteEntry =
  | ({ kind: "craft" } & ResolvedCraftStep)
  | { kind: "options"; step: CraftRouteOptions; recipes: readonly CraftRecipe[] };

/** One line of the shopping list. */
export interface ShoppingLine {
  id: number;
  name: string;
  count: number;
  /** The profession that makes it, when not bought or farmed raw. */
  madeBy?: string;
  /** For an item this profession makes on the way (bolts): what it takes, in total. */
  makesFrom?: CraftReagent[];
}
