"""Field definitions for each IRS tax form type.

Each entry maps form_name -> list of (field_id, field_label) pairs.
Used by the extraction service to create TaxFormField rows and by the
Claude prompt to know which boxes to extract.
"""

TAX_FORM_FIELD_DEFINITIONS: dict[str, list[tuple[str, str]]] = {
    "w2": [
        ("box_1", "Wages, tips, other compensation"),
        ("box_2", "Federal income tax withheld"),
        ("box_3", "Social security wages"),
        ("box_4", "Social security tax withheld"),
        ("box_5", "Medicare wages and tips"),
        ("box_6", "Medicare tax withheld"),
        ("box_7", "Social security tips"),
        ("box_8", "Allocated tips"),
        ("box_10", "Dependent care benefits"),
        ("box_11", "Nonqualified plans"),
        ("box_12a", "Box 12a code and amount"),
        ("box_12b", "Box 12b code and amount"),
        ("box_12c", "Box 12c code and amount"),
        ("box_12d", "Box 12d code and amount"),
        ("box_13_statutory", "Statutory employee"),
        ("box_13_retirement", "Retirement plan"),
        ("box_13_sick_pay", "Third-party sick pay"),
        ("box_14", "Other"),
        ("box_15_state", "State"),
        ("box_16", "State wages, tips, etc."),
        ("box_17", "State income tax"),
        ("box_18", "Local wages, tips, etc."),
        ("box_19", "Local income tax"),
        ("box_20", "Locality name"),
    ],
    "1099_int": [
        ("box_1", "Interest income"),
        ("box_2", "Early withdrawal penalty"),
        ("box_3", "Interest on U.S. Savings Bonds and Treasury obligations"),
        ("box_4", "Federal income tax withheld"),
        ("box_5", "Investment expenses"),
        ("box_6", "Foreign tax paid"),
        ("box_8", "Tax-exempt interest"),
        ("box_9", "Specified private activity bond interest"),
        ("box_10", "Market discount"),
        ("box_11", "Bond premium"),
        ("box_12", "Bond premium on Treasury obligations"),
        ("box_13", "Bond premium on tax-exempt bond"),
    ],
    "1099_div": [
        ("box_1a", "Total ordinary dividends"),
        ("box_1b", "Qualified dividends"),
        ("box_2a", "Total capital gain distributions"),
        ("box_2b", "Unrecaptured Section 1250 gain"),
        ("box_2c", "Section 1202 gain"),
        ("box_2d", "Collectibles (28%) gain"),
        ("box_2e", "Section 897 ordinary dividends"),
        ("box_2f", "Section 897 capital gain"),
        ("box_3", "Nondividend distributions"),
        ("box_4", "Federal income tax withheld"),
        ("box_5", "Section 199A dividends"),
        ("box_6", "Investment expenses"),
        ("box_7", "Foreign tax paid"),
        ("box_9", "Cash liquidation distributions"),
        ("box_10", "Noncash liquidation distributions"),
        ("box_11", "Exempt-interest dividends"),
        ("box_12", "Specified private activity bond interest dividends"),
    ],
    "1099_b": [
        ("box_1a", "Description of property"),
        ("box_1b", "Date acquired"),
        ("box_1c", "Date sold or disposed of"),
        ("box_1d", "Proceeds"),
        ("box_1e", "Cost or other basis"),
        ("box_1f", "Accrued market discount"),
        ("box_1g", "Wash sale loss disallowed"),
        ("box_2", "Short-term or long-term"),
        ("box_4", "Federal income tax withheld"),
        ("box_5", "Noncovered security"),
        ("box_6", "Reported to IRS (gross or net)"),
    ],
    "1099_k": [
        ("box_1a", "Gross amount of payment card/third-party network transactions"),
        ("box_1b", "Card not present transactions"),
        ("box_2", "Merchant category code"),
        ("box_3", "Number of payment transactions"),
        ("box_4", "Federal income tax withheld"),
        ("box_5a", "January"),
        ("box_5b", "February"),
        ("box_5c", "March"),
        ("box_5d", "April"),
        ("box_5e", "May"),
        ("box_5f", "June"),
        ("box_5g", "July"),
        ("box_5h", "August"),
        ("box_5i", "September"),
        ("box_5j", "October"),
        ("box_5k", "November"),
        ("box_5l", "December"),
        ("box_6", "State"),
        ("box_7", "State ID number"),
        ("box_8", "State income tax withheld"),
    ],
    "1099_nec": [
        ("box_1", "Nonemployee compensation"),
        ("box_2", "Payer made direct sales totaling $5,000 or more"),
        ("box_4", "Federal income tax withheld"),
        ("box_5", "State tax withheld"),
        ("box_6", "State/Payer's state no."),
        ("box_7", "State income"),
    ],
    "1099_misc": [
        ("box_1", "Rents"),
        ("box_2", "Royalties"),
        ("box_3", "Other income"),
        ("box_4", "Federal income tax withheld"),
        ("box_5", "Fishing boat proceeds"),
        ("box_6", "Medical and health care payments"),
        ("box_8", "Substitute payments in lieu of dividends or interest"),
        ("box_9", "Payer made direct sales totaling $5,000 or more"),
        ("box_10", "Crop insurance proceeds"),
        ("box_11", "Foreign tax paid"),
        ("box_12", "Excess golden parachute payments"),
        ("box_13", "Nonqualified deferred compensation"),
        ("box_15", "State tax withheld"),
        ("box_16", "State/Payer's state no."),
        ("box_17", "State income"),
    ],
    "1099_r": [
        ("box_1", "Gross distribution"),
        ("box_2a", "Taxable amount"),
        ("box_2b_taxable_not_determined", "Taxable amount not determined"),
        ("box_2b_total_distribution", "Total distribution"),
        ("box_3", "Capital gain (included in box 2a)"),
        ("box_4", "Federal income tax withheld"),
        ("box_5", "Employee contributions/designated Roth contributions or insurance premiums"),
        ("box_6", "Net unrealized appreciation in employer's securities"),
        ("box_7", "Distribution code(s)"),
        ("box_8", "Other"),
        ("box_9a", "Your percentage of total distribution"),
        ("box_9b", "Total employee contributions"),
        ("box_10", "Amount allocable to IRR within 5 years"),
        ("box_11", "1st year of designated Roth contribution"),
        ("box_14", "State tax withheld"),
        ("box_15", "State/Payer's state no."),
        ("box_16", "State distribution"),
    ],
    "1098": [
        ("box_1", "Mortgage interest received from payer(s)/borrower(s)"),
        ("box_2", "Outstanding mortgage principal"),
        ("box_3", "Mortgage origination date"),
        ("box_4", "Refund of overpaid interest"),
        ("box_5", "Mortgage insurance premiums"),
        ("box_6", "Points paid on purchase of principal residence"),
        ("box_7", "Is the address of the property different from payer's address"),
        ("box_8", "Address of property securing the mortgage"),
        ("box_9", "Number of mortgaged properties"),
        ("box_10", "Other"),
        ("box_11", "Mortgage acquisition date"),
    ],
    "k1": [
        ("box_1", "Ordinary business income (loss)"),
        ("box_2", "Net rental real estate income (loss)"),
        ("box_3", "Other net rental income (loss)"),
        ("box_4", "Guaranteed payments for services"),
        ("box_5", "Interest income"),
        ("box_6a", "Ordinary dividends"),
        ("box_6b", "Qualified dividends"),
        ("box_7", "Royalties"),
        ("box_8", "Net short-term capital gain (loss)"),
        ("box_9a", "Net long-term capital gain (loss)"),
        ("box_9b", "Collectibles (28%) gain (loss)"),
        ("box_9c", "Unrecaptured Section 1250 gain"),
        ("box_10", "Net Section 1231 gain (loss)"),
        ("box_11", "Other income (loss)"),
        ("box_12", "Section 179 deduction"),
        ("box_13", "Other deductions"),
        ("box_14", "Self-employment earnings (loss)"),
        ("box_15", "Credits"),
        ("box_16", "Attach statement - foreign transactions"),
        ("box_17", "Alternative minimum tax (AMT) items"),
        ("box_18", "Tax-exempt income and nondeductible expenses"),
        ("box_19", "Distributions"),
        ("box_20", "Other information"),
        ("box_21", "Foreign country or U.S. possession"),
    ],
    "1095_a": [
        ("box_1", "Marketplace identifier"),
        ("box_2", "Marketplace-assigned policy number"),
        ("box_3", "Policy issuer's name"),
        ("box_7", "Policy start date"),
        ("box_8", "Policy termination date"),
        ("box_11a", "City or town"),
        ("box_11b", "State"),
        ("box_11c", "ZIP code"),
        ("box_21", "Monthly enrollment premium (January)"),
        ("box_22", "Monthly enrollment premium (February)"),
        ("box_23", "Monthly enrollment premium (March)"),
        ("box_24", "Monthly enrollment premium (April)"),
        ("box_25", "Monthly enrollment premium (May)"),
        ("box_26", "Monthly enrollment premium (June)"),
        ("box_27", "Monthly enrollment premium (July)"),
        ("box_28", "Monthly enrollment premium (August)"),
        ("box_29", "Monthly enrollment premium (September)"),
        ("box_30", "Monthly enrollment premium (October)"),
        ("box_31", "Monthly enrollment premium (November)"),
        ("box_32", "Monthly enrollment premium (December)"),
        ("box_33", "Monthly SLCSP premium (annual)"),
        ("box_34", "Monthly advance payment of PTC (annual)"),
    ],
}

TAX_SOURCE_FORM_TYPES: set[str] = {
    "w2", "1099_int", "1099_div", "1099_b", "1099_k",
    "1099_misc", "1099_nec", "1099_r", "1098", "k1", "1095_a",
}
