"""Boot-time platform-admin seeding — the multi-user counterpart of the
single-user ``SEED_USER_*`` operator seed.

Multi-user apps (public ``/auth/register`` mounted) set::

    SEED_ADMIN_EMAIL=<operator email>
    SEED_ADMIN_PASSWORD_HASH=<bcrypt hash — NEVER the plaintext password>

and pass ``seed_admin=build_seed_admin_hook(...)`` to
``platform_shared.core.lifespan.create_app_lifespan``. On every boot the hook
ensures a fully-verified platform admin (``role=ADMIN`` + ``is_superuser``)
exists for that email. Idempotent — reruns are no-ops.

Security posture (the parts that are NOT negotiable):

* **Promote only a row the seed owns.** Multi-user apps have open
  registration, and the admin email is typically public. If a user row with
  ``SEED_ADMIN_EMAIL`` exists but its ``hashed_password`` differs from
  ``SEED_ADMIN_PASSWORD_HASH``, the row was NOT created by this seed — it is
  either the operator after an in-app password change (already promoted on a
  previous boot) or an attacker squatting the address. Either way the seed
  REFUSES to touch it: no role promotion, no ``is_verified`` flip. An
  email-string match alone is never proof of ownership.
* **Reserve the address from public registration.**
  :class:`platform_shared.auth.user_manager.PlatformBaseUserManager` rejects
  register attempts for the configured ``seed_admin_email`` exactly as it
  would an already-taken email (no enumeration signal).
* **Never log the hash.** A bcrypt hash is crackable credential material.
  Error messages name the env var; they never echo its value.

To generate the hash locally (the password never leaves your terminal)::

    python -c "from passlib.context import CryptContext; import getpass; \
      print(CryptContext(schemes=['bcrypt']).hash(getpass.getpass('password: ')))"

A freshly seeded admin can use ``role=ADMIN`` routes immediately, but the
strict superuser gate additionally requires TOTP — enroll 2FA right after the
first login to unlock ``is_superuser`` routes.
"""
from __future__ import annotations

import logging
import re
from collections.abc import AsyncIterator, Awaitable, Callable
from contextlib import AbstractAsyncContextManager
from typing import Any, Protocol

from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from platform_shared.core.auth_events import AuthEventType
from platform_shared.core.permissions import Role
from platform_shared.services.auth_event_service import log_auth_event

logger = logging.getLogger(__name__)

# passlib bcrypt output: $2b$<2-digit cost>$<22-char salt><31-char digest>.
# $2a$/$2y$ are accepted for hashes generated by other bcrypt frontends.
_BCRYPT_HASH_RE = re.compile(r"^\$2[aby]\$\d{2}\$[./A-Za-z0-9]{53}$")


class SeedAdminNotConfiguredError(RuntimeError):
    """Raised in production when the seed is required (or half-configured)
    but SEED_ADMIN_EMAIL / SEED_ADMIN_PASSWORD_HASH is empty."""


class SeedAdminInvalidEmailError(RuntimeError):
    """Raised in production when SEED_ADMIN_EMAIL is set but not a valid email."""


class SeedAdminInvalidHashError(RuntimeError):
    """Raised in production when SEED_ADMIN_PASSWORD_HASH is not a bcrypt hash
    (e.g. a plaintext password was pasted, or the ``$`` got shell-mangled)."""


def is_valid_seed_email(email: str) -> bool:
    """Return True if *email* passes the same validation fastapi-users'
    ``UserRead.email`` (Pydantic ``EmailStr``) applies at response time.

    Pydantic v2 ``EmailStr`` delegates to ``email-validator`` with
    ``check_deliverability=False`` (no DNS/network). We mirror that exactly so
    this boot check accepts/rejects precisely what the response schema will —
    catching ``dev@localhost``-style addresses (no dot in the domain) before
    they seed an account whose ``GET /users/me`` then 500s on every call.

    The DNS check is deliberately disabled: it matches Pydantic, avoids a
    network call on the startup path, and keeps the check deterministic in CI.
    """
    if not email:
        return False
    try:
        from email_validator import EmailNotValidError, validate_email
    except ImportError:  # pragma: no cover - ships with pydantic[email]/fastapi-users
        # Minimal structural fallback: local-part@domain with a dotted domain.
        parts = email.split("@")
        return len(parts) == 2 and bool(parts[0]) and "." in parts[1]
    try:
        validate_email(email, check_deliverability=False)
        return True
    except EmailNotValidError:
        return False


def is_bcrypt_hash(value: str) -> bool:
    """Cheap structural check that *value* is a bcrypt hash string.

    Catches the two realistic misconfigurations — a plaintext password pasted
    into the env var, and a hash whose ``$`` characters were eaten by shell
    interpolation — before they silently seed an account nobody can log into.
    """
    return bool(_BCRYPT_HASH_RE.match(value or ""))


def is_reserved_seed_email(email: str, seed_admin_email: str) -> bool:
    """True when *email* is the configured seed-admin address (case-insensitive).

    Used by ``PlatformBaseUserManager.create`` to keep the admin address out
    of public registration. Empty ``seed_admin_email`` reserves nothing.
    """
    if not seed_admin_email:
        return False
    return (email or "").strip().lower() == seed_admin_email.strip().lower()


async def seed_admin_user(
    db: AsyncSession,
    *,
    user_model: Any,
    email: str,
    password_hash: str,
) -> str:
    """Ensure a verified platform admin exists for *email*. Idempotent.

    Returns the action taken — ``"created"``, ``"promoted"``, ``"unchanged"``,
    or ``"refused"`` (row exists but its hash doesn't match: squatted address
    or operator changed their password in-app; see module docstring).

    The lookup is case-insensitive to match fastapi-users' own
    ``get_by_email`` — otherwise a squatter registering a case-variant of the
    address would slip past the ownership check and the seed would insert a
    duplicate.
    """
    result = await db.execute(
        select(user_model).where(
            func.lower(user_model.email) == email.strip().lower()
        )
    )
    existing = result.scalars().first()

    if existing is None:
        user = user_model(
            email=email,
            hashed_password=password_hash,
            is_active=True,
            is_superuser=True,
            is_verified=True,  # operator's own address — no verification email needed
            role=Role.ADMIN,
        )
        db.add(user)
        await db.flush()
        await log_auth_event(
            db,
            event_type=AuthEventType.SEED_ADMIN_CREATED,
            user_id=user.id,
            succeeded=True,
        )
        logger.info("seed_admin_user: created platform admin %s", email)
        return "created"

    if existing.hashed_password != password_hash:
        # NOT seed-owned. Promoting on an email-string match alone would hand
        # admin to whoever registered the address first (open registration).
        # Also covers the benign case: the operator changed their password
        # in-app after a previous boot already promoted them.
        await log_auth_event(
            db,
            event_type=AuthEventType.SEED_ADMIN_REFUSED,
            user_id=existing.id,
            succeeded=False,
            metadata={"reason": "hash_mismatch"},
        )
        logger.error(
            "seed_admin_user: a user with SEED_ADMIN_EMAIL exists but its "
            "password hash does not match SEED_ADMIN_PASSWORD_HASH — refusing "
            "to promote. If the operator changed their password in-app this "
            "is expected (already promoted); otherwise investigate the "
            "seed_admin.refused auth event (user_id=%s).",
            existing.id,
        )
        return "refused"

    updates: dict[str, Any] = {}
    if existing.role != Role.ADMIN:
        updates["role"] = Role.ADMIN
    if not existing.is_superuser:
        updates["is_superuser"] = True
    if not existing.is_verified:
        updates["is_verified"] = True
    if not existing.is_active:
        updates["is_active"] = True

    if not updates:
        return "unchanged"

    for field, value in updates.items():
        setattr(existing, field, value)
    await db.flush()
    await log_auth_event(
        db,
        event_type=AuthEventType.SEED_ADMIN_PROMOTED,
        user_id=existing.id,
        succeeded=True,
        metadata={"fields": sorted(updates)},
    )
    logger.info(
        "seed_admin_user: promoted existing seed-owned user %s to platform "
        "admin (fields: %s)", email, ", ".join(sorted(updates)),
    )
    return "promoted"


class _SeedAdminSettings(Protocol):
    """The Settings shape the hook builder needs (BaseAppSettings satisfies it)."""

    seed_admin_email: str
    seed_admin_password_hash: str
    environment: str


def build_seed_admin_hook(
    *,
    settings: _SeedAdminSettings,
    unit_of_work: Callable[[], AbstractAsyncContextManager[AsyncSession]],
    user_model: Any,
    required: bool = False,
) -> Callable[[], Awaitable[None]]:
    """Build the ``seed_admin`` lifespan hook for one app.

    Args:
        settings: The app's settings object — read at hook-run time (not
            build time) so tests and reloads see current values.
        unit_of_work: The app's ``app.db.session.unit_of_work`` context
            manager factory. The seed runs in one committed transaction.
        user_model: The app's ``User`` ORM class. Must declare the platform
            ``role`` column (see ``platform_shared.core.permissions``).
        required: When True, production boot FAILS LOUD while the env vars
            are blank — same posture as the other boot guards, for apps whose
            deploy contract says the admin must exist (the deploy healthcheck
            fails and the rollout rolls back). When False (default), blank
            vars skip the seed silently so apps that never adopted the
            standard are unaffected.

    Validation order: presence → email format → hash format. In production
    every failure raises (deploy rolls back); in dev it logs and skips so a
    half-configured local env still boots.
    """

    async def _seed_admin() -> None:
        email = settings.seed_admin_email.strip()
        password_hash = settings.seed_admin_password_hash.strip()
        production = settings.environment == "production"

        if not email and not password_hash:
            if required and production:
                raise SeedAdminNotConfiguredError(
                    "SEED_ADMIN_EMAIL and SEED_ADMIN_PASSWORD_HASH must be set "
                    "in production for this app. Set them via the seed-env "
                    "workflow (<APP>_SEED_ADMIN_* repo secrets) or directly in "
                    "backend/.env.docker."
                )
            logger.info(
                "seed_admin: SEED_ADMIN_EMAIL/SEED_ADMIN_PASSWORD_HASH not set "
                "— skipping platform-admin seed."
            )
            return

        if not email or not password_hash:
            # Half-configured is always a misconfiguration, required or not.
            if production:
                raise SeedAdminNotConfiguredError(
                    "Exactly one of SEED_ADMIN_EMAIL / SEED_ADMIN_PASSWORD_HASH "
                    "is set — both are needed. Values are never logged; check "
                    "backend/.env.docker."
                )
            logger.warning(
                "seed_admin: only one of SEED_ADMIN_EMAIL / "
                "SEED_ADMIN_PASSWORD_HASH is set — skipping seed in "
                "non-production environment."
            )
            return

        if not is_valid_seed_email(email):
            if production:
                raise SeedAdminInvalidEmailError(
                    f"SEED_ADMIN_EMAIL={email!r} is not a valid email address. "
                    "fastapi-users serializes users through an EmailStr field, "
                    "so an invalid address makes GET /users/me 500 for this "
                    "account. Set a valid address in backend/.env.docker."
                )
            logger.error(
                "seed_admin: SEED_ADMIN_EMAIL=%r is not a valid email address "
                "— skipping seed. GET /users/me would 500 for this account.",
                email,
            )
            return

        if not is_bcrypt_hash(password_hash):
            # Never echo the value — it may be a plaintext password.
            if production:
                raise SeedAdminInvalidHashError(
                    "SEED_ADMIN_PASSWORD_HASH is not a bcrypt hash (expected "
                    "$2b$... format). Did a plaintext password get pasted, or "
                    "did shell interpolation eat the $ characters? Regenerate "
                    "with: python -c \"from passlib.context import "
                    "CryptContext; import getpass; print(CryptContext("
                    "schemes=['bcrypt']).hash(getpass.getpass()))\""
                )
            logger.error(
                "seed_admin: SEED_ADMIN_PASSWORD_HASH is not a bcrypt hash — "
                "skipping seed. Login would silently never work for this "
                "account. (Value not logged.)"
            )
            return

        async with unit_of_work() as db:
            await seed_admin_user(
                db, user_model=user_model, email=email, password_hash=password_hash,
            )

    return _seed_admin
